import { PAYMENT_REQUEST_ABI } from './PaymentRequest.abi'
import { PAYMENT_REQUEST_V1_ABI } from './PaymentRequestV1.abi'

export const DEFAULT_CONTRACT_ADDRESS =
  '0x298c05FDECb261287873B17f5dACa53b3D5ed3c2' as const

export const DEFAULT_CONTRACT_VERSION = 'v2' as const

export const DEFAULT_CONTRACT_DEPLOYMENT_BLOCK = 5775085n

export const CONTRACT_ADDRESS =
  (process.env.NEXT_PUBLIC_CONTRACT_ADDRESS ?? DEFAULT_CONTRACT_ADDRESS) as `0x${string}`

export const CONTRACT_VERSION =
  process.env.NEXT_PUBLIC_CONTRACT_VERSION === 'v1'
    ? 'v1'
    : DEFAULT_CONTRACT_VERSION

export const CONTRACT_DEPLOYMENT_BLOCK = BigInt(
  process.env.NEXT_PUBLIC_CONTRACT_DEPLOYMENT_BLOCK ?? DEFAULT_CONTRACT_DEPLOYMENT_BLOCK,
)

export const CONTRACT_ABI =
  CONTRACT_VERSION === 'v2' ? PAYMENT_REQUEST_ABI : PAYMENT_REQUEST_V1_ABI
